Document: moarvm
Title: Debian moarvm Manual
Author: <insert document author here>
Abstract: This manual describes what moarvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/moarvm/moarvm.sgml.gz

Format: postscript
Files: /usr/share/doc/moarvm/moarvm.ps.gz

Format: text
Files: /usr/share/doc/moarvm/moarvm.text.gz

Format: HTML
Index: /usr/share/doc/moarvm/html/index.html
Files: /usr/share/doc/moarvm/html/*.html
