
#ifndef PARROT_MVMCC_OPS_H_GUARD
#define PARROT_MVMCC_OPS_H_GUARD


/* ex: set ro:
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 *
 * This file is generated automatically from 'mvmcc.ops' (and possibly other
 * .ops files). by ops2c.nqp.
 *
 * Any changes made here will be lost!  To regenerate this file after making
 * changes to any ops, use the bootstrap-ops makefile target.
 *
 */
#define PARROT_IN_EXTENSION

#include "parrot/parrot.h"
#include "parrot/oplib.h"
#include "parrot/runcore_api.h"


op_lib_t *Parrot_DynOp_mvmcc_4_3_0(PARROT_INTERP, long init);

PARROT_DYNEXT_EXPORT opcode_t * Parrot_mvm_compiler_setup(opcode_t *, PARROT_INTERP);


#endif /* PARROT_MVMCC_OPS_H_GUARD */


/*
 * Local variables:
 *   c-file-style: "parrot"
 *   buffer-read-only: t
 * End:
 * vim: expandtab shiftwidth=4:
 */
